# Generated by Django 5.0.4 on 2024-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_runner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjobmodel',
            old_name='is_executed',
            new_name='clockedsched_executed',
        ),
        migrations.AddField(
            model_name='cronjobmodel',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
