apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: schedule-queue-system
spec:
  replicas: 1
  image: rabbitmq:4-management
  service:
    type: ClusterIP
  rabbitmq:
    additionalConfig: |
      loopback_users.guest = false