apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: schedule-queue-system
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: sqs-sa
      initContainers:
      - name: setup-cookie
        image: busybox:1.35
        command: ['sh', '-c', 'echo -n "SWQOKODSQALRPCLNMEQG" > /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie && chown 999:999 /var/lib/rabbitmq/.erlang.cookie']
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management-alpine
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: RABBITMQ_PASSWORD
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command: ['sh', '-c', 'rabbitmq-diagnostics check_running && rabbitmq-diagnostics check_local_alarms']
          initialDelaySeconds: 60  # Increased to give more startup time
          periodSeconds: 30
          timeoutSeconds: 10      # Increased timeout
          failureThreshold: 5     # Increased to be more forgiving
        readinessProbe:
          exec:
            command: ['sh', '-c', 'rabbitmq-diagnostics check_running']
          initialDelaySeconds: 30 # Increased to give more startup time
          periodSeconds: 10
          timeoutSeconds: 10      # Increased timeout
          failureThreshold: 5     # Increased to be more forgiving
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi